select
Case When MONTH(DocDate) = '1' then N'มกราคม'
	when MONTH(DocDate) = '2' then N'กุมภาพันธ์'
	when MONTH(DocDate) = '3' then N'มีนาคม'
	when MONTH(DocDate) = '4' then N'เมษายน'
	when MONTH(DocDate) = '5' then N'พฤษภาคม'
	when MONTH(DocDate) = '6' then N'มิถุนายน'
	when MONTH(DocDate) = '7' then N'กรกฎาคม'
	when MONTH(DocDate) = '8' then N'สิงหาคม'
	when MONTH(DocDate) = '9' then N'กันยายน'
	when MONTH(DocDate) = '10' then N'ตุลาคม'
	when MONTH(DocDate) = '11' then N'พฤศจิกายน'
	when MONTH(DocDate) = '12' then N'ธันวาคม'
	else 'XX'
	end 'MonthDoc'
